# Generated by Django 5.2.8 on 2025-11-19 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expiry_hours', models.IntegerField(choices=[(1, '1 Hour'), (24, '24 Hours'), (72, '3 Days'), (168, '7 Days'), (720, '30 Days')], default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_downloads', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='fileshare.sharedfile')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharedfile',
            index=models.Index(fields=['token'], name='fileshare_s_token_6b607e_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedfile',
            index=models.Index(fields=['expires_at'], name='fileshare_s_expires_1f5338_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['shared_file', '-downloaded_at'], name='fileshare_d_shared__e837b4_idx'),
        ),
    ]
